### PR TITLE
Adding .idea specific gitignore

### PR DESCRIPTION
**Pull request by Gigi-Didberidze**
Testing the PR and protection rules with a basic gitignore change.

### CODE REVIEW

**Review by gezabohus — APPROVED** [review]
Hey Giogi,

I agree with the necessity of this, but wouldn't it be simpler just to exclude .idea without all the itemization?

Also, I am not familiar with all the items you listed outside of .idea, so I can't ocmment on that.

**Comment by Gigi-Didberidze** [comment]
The items mentioned outside .idea are part of Python project .gitignore template.  

I can uncomment .idea/ instead of its itemization (the reason I used the itemization is because it wasn't a recommended option, but makes sense to just uncomment it, so I can update that).

In addition to this, should I only include the items that need to be ignored for this specific project instead of using the whole template?

**Comment by gezabohus** [comment]
I would exclude .idea and other build artifacts in general, not only for this project.

**Comment by Gigi-Didberidze** [comment]
I just modified the file. I am uncommenting the necessary items for now and I commented out the ones that might be useful for later. Hence, this file will be updated according to further modifications of the project.

**Review by gezabohus — APPROVED** [review]

**Pull request merged**
